### ISSUE TITLE
Perlcode needs double ;;

### ISSUE THREAD

**Issue by sidey79** [heinz-otto/fhemcl#2]
Versucht man Perlcode über fhemcl.sh zu verarbeiten, dann klappt das nicht, wenn z.B. am Ende der Zeile nur ein Semikolon steht:

` my $dmsg ="W84#FE42004526";
`
Mit zweien funktioniert es dann:
` my $dmsg ="W84#FE42004526";;`

Sollten man das eventuell im Script automatisch wandeln oder besser nicht. Ich wäre eigentlich für automatisch, eventuell über einen Schalter?

**Comment by heinz-otto** [comment]
Ich bin in meiner Umsetzung grundlegend davon ausgegangen, dass der Code so aussehen muss wie in der Raw Def bzw. so wie ich ihn in der FHEM Kommandozeile eingeben muss. 
Und da ist es ja genauso: die ; müssen im Perl Code doppelt sein.
Ich wollte quasi nur die Schnittstelle Script fähig machen, das andere ist ja FHEM.

**Comment by sidey79** [comment]
Ja okay. Das verstehe ich. Das sollte dann nicht geändert werden.
